# Generated by Django 4.2.7 on 2025-09-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='image',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_offline_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
