# Generated by Django 4.2.7 on 2025-09-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0003_add_facial_recognition_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
